const canvasElem = document.getElementById("canvas");
const ctx = canvasElem.getContext("2d");

ctx.beginPath();
ctx.arc(30, 35, 15, 0, 2 * Math.PI, false);
ctx.fillStyle = '#FFFFFF';
ctx.fill();
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.arc(70, 75, 15, 0, 2 * Math.PI, false);
ctx.fillStyle = '#D5D8DC';
ctx.fill();
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.arc(110, 115, 15, 0, 2 * Math.PI, false);
ctx.fillStyle = '#BDBDBD';
ctx.fill();
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.arc(150, 155, 15, 0, 2 * Math.PI, false);
ctx.fillStyle = '#A4A4A4';
ctx.fill();
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.arc(190, 195, 15, 0, 2 * Math.PI, false);
ctx.fillStyle = '#585858';
ctx.fill();
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.arc(230, 235, 15, 0, 2 * Math.PI, false); //6
ctx.fillStyle = '#2E2E2E';
ctx.fill();
ctx.stroke();
ctx.closePath();